version: '3.8'

services:
  user-service:
    build: ./user-service
    ports:
      - "3004:3004"
    networks:
      - micro-network

  product-service:
    build: ./product-service
    ports:
      - "3001:3001"
    networks:
      - micro-network

  order-service:
    build: ./order-service
    ports:
      - "3002:3002"
    networks:
      - micro-network

  gateway-service:
    build: ./gateway-service
    ports:
      - "3003:3003"
    environment:
      - USER_SERVICE_URL=http://user-service:3004
      - PRODUCT_SERVICE_URL=http://product-service:3001
      - ORDER_SERVICE_URL=http://order-service:3002
    networks:
      - micro-network

networks:
  micro-network:
    driver: bridge
